name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'bun'

      - name: Install dependencies
        run: bun install

      - name: Build
        env:
          VITE_COGNITO_API_KEY: ${{ secrets.COGNITO_API_KEY }}
          VITE_COGNITO_ORG_KEY: ${{ secrets.COGNITO_ORG_KEY }}
          VITE_USERNAME: ${{secrets.USERNAME}}
          VITE_PASSWORD: ${{secrets.PASSWORD}}
        run: bun run build:client

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public
